TEST/simple_forms/urls.py
#coding: utf-8

from django.conf import settings
from django.conf.urls import url ,include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from simple_forms.apps.core import views
from simple_forms.apps.core import forms

urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^$', views.calendar, name='home'),
    url(r'^calendar/$', views.calendar, name='calendar'),
    url(r'^patients/$', views.patients, name='patients'),
    url(r'^add/$', views.add_person, name='add_person'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^password_reset/$', auth_views.password_reset,
        {'template_name': "core/password_reset.html",
         'from_email': 'Password_reset@ezclinic16.appspotmail.com',
         'password_reset_form': forms.AppEnginePasswordResetForm},
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done,
        {'template_name': "core/password_reset_done.html"}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'set_password_form': forms.SetPasswordForm,
        'template_name': "core/password_reset_confirm.html"},  name='password_reset_confirm' ),
    url(r'^reset/done/$', auth_views.password_reset_complete,
        {'template_name': "core/password_reset_complete.html"},
        name='password_reset_complete'),
    url(r'^(?P<person_id>\d+)/delete/$', views.delete_person, name='delete_person'),
    url(r'^(?P<person_id>\d+)/image/(?P<image_id>\d+)/delete/$', views.delete_person_image, name='delete_person_image'),
    url(r'^(?P<person_id>\d+)/diagcode/(?P<diagcode_id>\d+)/delete/$', views.delete_person_diagcode, name='delete_person_diagcode'),
    url(r'^(?P<person_id>\d+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<person_id>\d+)/view/$', views.view, name='view'),
    url(r'^(?P<person_id>\d+)/foto/$', views.foto, name='foto'),
    url(r'^(?P<person_id>\d+)/appointment/$',
        views.AppointmentView.as_view(),
        name='appointment'),
    url(r'^(?P<person_id>\d+)/receipt/$',
        views.ReceiptView.as_view(),
        name='receipt'),
    url(r'^search/$', views.search, name='search'),
	url(r'^_ah/', include('djangae.urls')),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^google323523d1a2bbb38c\.html$', lambda r: HttpResponse("google-site-verification: google323523d1a2bbb38c.html", mimetype="text/plain")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TEST/simple_forms/apps/core/models.py
from __future__ import unicode_literals
import logging
import json
from decimal import Decimal

#from django.contrib.auth.models import Permission, User
from datetime import date
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Permission
from django.db import models
from django.utils.translation import ugettext_lazy as _

from djangae import fields, storage
from djangae.db import transaction
from django_countries.fields import CountryField

STATUS_CHOICES = (
    ("Unmarried", ("Unmarried")),
    ("Married", ("Married")),
)

SEX_CHOICES = (
    ("Male", ("Male")),
    ("Female", ("Female")),
)

DENTAL_CHART_CHOICES = (
    ("Deciduous", ("Deciduous")),
    ("Permanent", ("Permanent")),
)


public_storage = storage.CloudStorage(
    bucket='ezclinic16.appspot.com', google_acl='public-read')


class User(AbstractUser):
    email = models.EmailField(_('email address'), unique=True, null=False, blank=False)

    country = CountryField()
    city = models.CharField(max_length=30)
    clinic = models.CharField(max_length=30)


class Person(models.Model):
    user = models.ForeignKey(User, default=1)
    name = models.CharField(max_length=250, null=True)
    last_name = models.CharField(max_length=500)
    age = models.IntegerField(default=100)
    martial_status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default=("Single"))
    sex = models.CharField( max_length=20, choices=SEX_CHOICES, default=("Male"))
    mobile = models.CharField(max_length=26, default=0011)
    amount_paid = models.DecimalField("money paid", max_digits=10,
                                      decimal_places=2, null=False, default=0)
    amount_left = models.DecimalField("total price", max_digits=10,
                                      decimal_places=2, null=False, default=0)
    note = models.CharField(max_length=256, null=True, blank=True)
    address = models.CharField(max_length=256, null=True, blank=True)
    date = models.DateField(("Date"), default=date.today, blank=True)
    time = models.TimeField(("Time"), null=True, blank=True)
    chief_complain = models.CharField(max_length=256, null=True, blank=True)
    treatment_plan = models.CharField(max_length=256, null=True, blank=True)
    treatment_done = models.CharField(max_length=256, null=True, blank=True)

    dental_chart_type = models.CharField(
            max_length=20, choices=DENTAL_CHART_CHOICES, default=("Permanent"))
    dental_chart = models.CharField(max_length=1024, default="{}")

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not isinstance(self.amount_paid, Decimal):
            self.amount_paid = Decimal(self.amount_paid or "0")
        if not isinstance(self.amount_left, Decimal):
            self.amount_left = Decimal(self.amount_left or "0")
        with transaction.atomic(xg=True):
            delta = 0
            if self.pk:
                old_state = Person.objects.get(pk=self.pk)
                delta = self.amount_paid - Decimal(old_state.amount_paid or "0")
            else:
                delta = self.amount_paid
            super(Person, self).save(*args, **kwargs)

        if delta > 0:
            Receipt.objects.create(user=self.user, person=self, amount=delta)

        try:
            dc = DentalChart.objects.get(person_id=self.pk)
        except DentalChart.DoesNotExist:
            dc = DentalChart(person_id=self.pk)
        dc.dental_chart_type = self.dental_chart_type
        dc.dental_chart = self.dental_chart
        dc.save()


class Receipt(models.Model):
    user = models.ForeignKey(User)
    person = models.ForeignKey(Person)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)


class Picture(models.Model):
    picture = models.FileField(
        upload_to='image', storage=public_storage, blank=True)
    person = models.ForeignKey(Person, related_name='pictures')

    def filename(self):

        return self.picture.name.split('/')[-1].split('.')[0]

    def __unicode__(self):
        return self.picture.url


class Diagcode(models.Model):
    diagcode = models.CharField(max_length=256)
    person = models.ForeignKey(Person, related_name='diagcodes')

    class Meta:
        unique_together = ('person', 'diagcode')

    def __unicode__(self):
        return self.diagcode

class DentalChart(models.Model):
    COLORS = {"x": "extraction",
              "red": "missing",
              "yellow": "filling",
              "green": "rct"}


    person = models.ForeignKey(Person, related_name='dental_charts')
    dental_chart_type = models.CharField(
            max_length=20, choices=DENTAL_CHART_CHOICES, default=("Permanent"))
    dental_chart = models.CharField(max_length=1024, default="{}")

    extraction = models.IntegerField(default=0)
    missing = models.IntegerField(default=0)
    filling = models.IntegerField(default=0)
    rct = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        data = json.loads(self.dental_chart)
        self.extraction = 0
        self.missing = 0
        self.filling = 0
        self.rct = 0

        for value in data.values():
            if value in self.COLORS:
                field = self.COLORS[value]
                setattr(self, field, 1 + getattr(self, field))
        super(DentalChart, self).save(*args, **kwargs)


class Event(models.Model):
    user = models.ForeignKey(User)
    text = models.TextField(default='', blank=True)
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

TEST/simple_forms/apps/core/forms.py
from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext, ugettext_lazy as _
from django.contrib.auth import (authenticate, get_user_model,
                                 password_validation)
from django.contrib.auth.forms import PasswordResetForm

from djangae.utils import get_in_batches

from . import models as m


class PersonForm(forms.ModelForm):
    pictures = forms.FileField(widget=forms.ClearableFileInput(
        attrs={'required': False, 'multiple': True, 'class': 'form-control'}), required=False)
    time = forms.TimeField(input_formats=["%I:%M %p"])

    class Meta:
        model = m.Person
        fields = ['name', 'last_name', 'age', 'martial_status', 'mobile', 'sex',
                  'amount_paid', 'amount_left', 'note', 'address', 'date', 'time',
                  'treatment_done', 'treatment_plan', 'chief_complain',
                   'dental_chart_type', 'dental_chart']
        widgets = {
            'name': forms.TextInput(attrs={'required': True, 'class': 'form-control',
                                           'placeholder': 'name'}),
            'last_name': forms.TextInput(attrs={'required': True, 'class': 'form-control',
                                                'placeholder': 'lastname'}),
            'age': forms.TextInput(attrs={'required': False, 'class': 'form-control',
                                          'placeholder': 'age'}),
            'amount_paid': forms.TextInput(attrs={'required': False, 'class': 'form-control',
                                                  'placeholder': 'amount paid'}),
            'amount_left': forms.TextInput(attrs={'required': False, 'class': 'form-control',
                                                  'placeholder': 'amount left'}),
            'note': forms.Textarea(attrs={'required': False, 'class': 'form-control',
                                           'placeholder': 'Patient History',
                                           'rows': '3'}),
            'address': forms.TextInput(attrs={'required': False, 'class': 'form-control',
                                              'placeholder': 'Current address'}),
            'chief_complain': forms.TextInput(attrs={'required': False, 'class': 'form-control',
                                                     'placeholder': 'chief complain'}),
            'treatment_plan': forms.Textarea(attrs={'required': False, 'class': 'form-control',
                                                    'placeholder': 'treatment plan', 'rows': '3'}),
            'treatment_done': forms.Textarea(attrs={'required': False, 'class': 'form-control',
                                                    'placeholder': 'treatment done', 'rows': '3'}),
            'dental_chart_type': forms.RadioSelect(),
            'dental_chart': forms.HiddenInput(),


        }


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = m.User
        fields = ['username', 'email', 'password', 'country',
                  'last_name', 'first_name', 'city', 'clinic']


class EventForm(forms.ModelForm):
    class Meta:
        model = m.Event
        fields = ['text', 'date']


class AppointmentForm(forms.Form):
    date = forms.DateField()
    time = forms.TimeField(input_formats=["%I:%M %p"], required=False)


class ReceiptForm(forms.ModelForm):
    class Meta:
        model = m.Receipt
        fields = ['amount']


class SetPasswordForm(forms.Form):
    """
    A form that lets a user change set their password without entering the old
    password
    """
    new_password = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        password = self.cleaned_data["new_password"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user


class AppEnginePasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label=_("Email"), max_length=254)

    def get_users(self, email):
        """Given an email, return matching user(s) who should receive a reset.

        This allows subclasses to more easily customize the default policies
        that prevent inactive users and users with unusable passwords from
        resetting their password.
        """
        active_users = list(get_user_model()._default_manager.filter(
            email__iexact=email, is_active=True))
        # Mild data migration
        # To use __iexact we have to resave models. Djangae do the rest
        # https://djangae.readthedocs.io/en/latest/db_backend/#special-indexes
        if len(active_users) == 0:
            for u in get_in_batches(
                    get_user_model()._default_manager.all(), 30):
                u.save()
            active_users = list(get_user_model()._default_manager.filter(
                email__iexact=email, is_active=True))

        return (u for u in active_users if u.has_usable_password())

TEST/simple_forms/apps/core/templates/core/base_visitor.html
{% load staticfiles %}
{% load cache %}
<!DOCTYPE html>
<html lang="en">
<title>ezClinic16</title>
<head>
    <meta charset="UTF-8">
    <!-- <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/> -->
	<link rel="icon" href="http://www.ezclinic16.appspot.com/favicon.ico" />
    <style>
        .input {
            margin-left: -0.5em;
        }
        .navbar{
            background-color: lightskyblue;
            color:white;
        }
        .registration-form {
            padding-top: 1em;
        }
    </style>
</head>
<body>
<nav class="navbar">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'login_user' %}">Log In</a></li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
<script type="text/javascript">
    window.yepnope=function(a,b){function c(){}function d(a){return Object(a)===a}function e(a){return"string"==typeof a}function f(){return"yn_"+q++}function g(){o&&o.parentNode||(o=b.getElementsByTagName("script")[0])}function h(a){return!a||"loaded"==a||"complete"==a||"uninitialized"==a}function i(b,c){c.call(a)}function j(a,j){var k,l,m;e(a)?k=a:d(a)&&(k=a._url||a.src,l=a.attrs,m=a.timeout),j=j||c,l=l||{};var q,r,t=b.createElement("script");m=m||n.errorTimeout,t.src=k,s&&(t.event="onclick",t.id=t.htmlFor=l.id||f());for(r in l)t.setAttribute(r,l[r]);t.onreadystatechange=t.onload=function(){if(!q&&h(t.readyState)){if(q=1,s)try{t.onclick()}catch(a){}i(k,j)}t.onload=t.onreadystatechange=t.onerror=null},t.onerror=function(){q=1,j(new Error("Script Error: "+k))},p(function(){q||(q=1,j(new Error("Timeout: "+k)),t.parentNode.removeChild(t))},m),g(),o.parentNode.insertBefore(t,o)}function k(f,h){var i,j,k={};d(f)?(i=f._url||f.href,k=f.attrs||{}):e(f)&&(i=f);var l=b.createElement("link");h=h||c,l.href=i,l.rel="stylesheet",l.media="only x",l.type="text/css",p(function(){l.media=k.media||"all"});for(j in k)l.setAttribute(j,k[j]);g(),o.parentNode.appendChild(l),p(function(){h.call(a)})}function l(a){var b=a.split("?")[0];return b.substr(b.lastIndexOf(".")+1)}function m(a,b){var c=a,d=[],e=[];for(var f in b)b.hasOwnProperty(f)&&(b[f]?d.push(encodeURIComponent(f)):e.push(encodeURIComponent(f)));return(d.length||e.length)&&(c+="?"),d.length&&(c+="yep="+d.join(",")),e.length&&(c+=(d.length?"&":"")+"nope="+e.join(",")),c}function n(a,b,c){var e;d(a)&&(e=a,a=e.src||e.href),a=n.urlFormatter(a,b),e?e._url=a:e={_url:a};var f=l(a);if("js"===f)j(e,c);else{if("css"!==f)throw new Error("Unable to determine filetype.");k(e,c)}}var o,p=a.setTimeout,q=0,r={}.toString,s=!(!b.attachEvent||a.opera&&"[object Opera]"==r.call(a.opera));return n.errorTimeout=1e4,n.injectJs=j,n.injectCss=k,n.urlFormatter=m,n}(window,document);
    yepnope("{% static "css/bootstrap.min.css" %}");
</script>
</body>
</html>

TEST/simple_forms/apps/core/templates/core/calendar.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load i18n %}

{% block content %}
<style>
  .page-header {
    padding: 1em 0 1em 0;
  }
  .page-header--h {
    line-height: 0;
  }
</style>
    <div class="row page-header">
      <div class="col-md-6">
        <h2 class="page-header--h">
        {% if today %}
        Today's Appointments
        {% else %}
        Appointments for {{ date|date:"F j"}}
        {% endif %}
      </h2>
      </div>
      <div class="col-md-6">
        <div class="pull-right">
        <button class="btn btn-info patients-datepicker" >
          <span class="glyphicon glyphicon-th"></span> {% trans "Check for other day" %}
        </button>
        <a href="{% url 'add_person' %}" class="btn btn-info">
          <span class="glyphicon glyphicon-plus"></span> {% trans  "Add Patient" %}
        </a>
        <button class="btn btn-info add-event" data-toggle="modal" data-target="#add-event-modal">
          <span class="glyphicon glyphicon-edit"></span> {% trans "Add reminder" %}
        </button>
      </div>
      </div>
    </div>
    <form id="patients-calendar-form" action="">
      <input id="patients-calendar-form-appointment" name="appointment" type="hidden">
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Lastname</th>
                <th class="col-md-3">Treatment done</th>
                <th class="col-md-3">Treatment plan</th>
                <th class="col-md-2 text-center">Appointment time</th>
                <th>Cancel</th>
                <th>View</th>
            </tr>
        </thead>
        <tbody>
            {% for person in persons %}
            <tr id="appointment-{{ person.id }}">
                <td>{{ person.name }}</td>
                <td>{{ person.last_name }}</td>
                <td>{{ person.treatment_done|linebreaks }}</td>
                <td>{{ person.treatment_plan|linebreaks }}</td>
                <td class="text-center">{{ person.time|time:"f A" }}</td>
                <td>
                    <button data-appointment-id="{{ person.id }}" type="button" class="cancel-button btn btn-xs btn-link">
                        <span  class="glyphicon glyphicon-minus"></span>
                    </button>
                </td>
                <td><a  href="{% url 'view' person.id %}"><i  class="glyphicon glyphicon-list-alt"></i></a></td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6" class="text-center">No result</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


  {% if events %}
  <h2> {% if today %}
        Today's Reminders
        {% else %}
        Reminders of {{ date|date:"F d"}}
        {% endif %}
    <button id="hide-events" class="btn btn-info pull-right" type="button">{% trans "Hide Reminders" %}</button>
  </h2>

  <div id="events-table" class="hidden">
    <table class="table">
      <tbody>
        {% for event in events %}
        <tr><td>{{ event.text }}</td></tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% endif %}

    {% if persons.has_other_pages %}
  <ul class="pagination">
    {% if persons.has_previous %}
      <li><a href="?page={{ persons.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in persons.paginator.page_range %}
      {% if persons.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if persons.has_next %}
      <li><a href="?page={{ persons.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

<div id="add-event-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">{% trans "Add reminder" %}</h4>
      </div>
      <form method="POST" id="add-event-form" class="form-horizontal">
        {% csrf_token %}
        <div class="modal-body">
          <div class="form-group">
            <label class="col-sm-2 control-label" for="{{ event_form.date.id_for_label }}">Date</label>
            <div class="col-sm-4">
              <div class="input-group date" data-provide="datepicker" data-date-autoclose="true" data-date-format="yyyy-mm-dd">
                {{ event_form.date|add_class:"form-control" }}
                <div class="input-group-addon">
                  <span class="glyphicon glyphicon-th"></span>
                </div>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label" for="{{ event_form.text.id_for_label }}">Reminder</label>
            <div class="col-sm-10">
              <textarea class="form-control" placeholder="Reminder" id="id_text" name="text" rows="10"></textarea>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>
  var key = 'events-state-{{ date|date:"Y-m-d" }}';
  // Default is show
  var events_shown = !! JSON.parse(window.localStorage[key] || "true");
 
  $(".patients-datepicker")
    .datepicker({autoClose: true, todayBtn: true, todayHighlight: true})
    .on("changeDate", function(event) {
      $("#patients-calendar-form-appointment").val(event.format("yyyy-mm-dd"));
      $("#patients-calendar-form").submit();
    });

  if (!events_shown) {
    $("#events-table").hide();
    $("#hide-events").html("Show Reminders");
  }
  $("#events-table").removeClass("hidden");
  
  $("#hide-events").click(function() {
    events_shown = ! events_shown;
    window.localStorage[key] = events_shown;
    if (events_shown) {
      $("#events-table").show();
      $("#hide-events").html("Hide Reminders");
    } else {
      $("#events-table").hide();
      $("#hide-events").html("Show Reminders");
    }

  });
</script>
  <script>
    var hidden_persons = JSON.parse(localStorage["hidden_persons"] || "[]");
    for (var i = 0; i < hidden_persons.length; i++) {
      $("#appointment-" + hidden_persons[i]).hide();
    }

    $(".cancel-button").click(function () {
      var user_id = $(this).data("appointment-id");
      bootbox.confirm("Are you sure you want to cancel an appointment?", function(confirmed) {
        if (confirmed) {
          hidden_persons.push(user_id);
          localStorage["hidden_persons"] = JSON.stringify(hidden_persons);
          $("#appointment-" + user_id).hide();
        }
      });
    });
  </script>
{% endblock %}

TEST/simple_forms/apps/core/templates/core/dashboard.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<style>
  .charts-dental-chart {
    border-bottom: 1px solid #888;
    border-right: 1px solid #888;
  }
  .charts-ages {
    border-bottom: 1px solid #888;
  }
  .charts-dental-chart--container {
    width: 100%;
  }
  .charts-ages--container {
    width: 100%;
  }
  .charts-patients {
    padding-top: 4rem;
  }
  .charts-revenue {
    padding-top: 4rem;
  }
</style>

<section>
  <h3>General statistics:</h3>
  <p>Total number of patients: {{ count }}</p>
  <p>Number of appointments in the next week: {{ appointment_next_week }}</p>
  <p>Number of appointments in the week after next: {{ appointment_next_week2 }}</p>
</section>
<div class="row">
<section class="col-sm-6 charts-dental-chart">
  <div class="charts-dental-chart--container"></div>
</section>
<section class="col-sm-6 charts-ages">
  <div class="charts-ages--container"></div>
</section>
</div>
<section class="charts-patients">
  <div class="charts-patients--container"></div>
</section>
<section class="charts-revenue">
  <div class="charts-revenue--container"></div>
</section>
<script src="{% static "highcharts/highcharts.js" %}"></script>
<script>
  Highcharts.chart(document.querySelector(".charts-ages--container"),
    {{ ages|safe }});
  Highcharts.chart(document.querySelector(".charts-dental-chart--container"),
    {{ dental_charts|safe }});
  Highcharts.chart(document.querySelector(".charts-patients--container"),
    {{ patients|safe }});
  Highcharts.chart(document.querySelector(".charts-revenue--container"),
    {{ revenue|safe }});
</script>
{% endblock %}

TEST/simple_forms/apps/core/templates/core/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-12">{{ field }}</div>
    </div>
{% endfor %}

TEST/simple_forms/apps/core/templates/core/home3.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% block content %}


{% if persons.pictures %}
	{% for picture in persons.pictures.all %}
    <div style="margin-top: 50px;" class="col-md-4">
        <div class="thumbnail">
            
                
                    <a class="fancybox" rel="group" href="{{ picture.picture.url }}">
                    <img src="{{ picture.picture.url }}" style="min-height:50px;height:250px;width:100%" alt="" />
                    </a>
        </div>
    </div>
	{% endfor %}
{% endif %}


<script src="{% static 'fancybox/source/jquery.fancybox.pack.js' %}" ></script>
   <script type="text/javascript">
       $(document).ready(function() {
            $(".fancybox")
                .attr('rel', 'group')
                .fancybox({
                    type: 'image',
                    padding: 0,
                    closeBtn : false,
                    fitToView: false, // avoids scaling the image to fit in the viewport
                    nextSpeed : 0, 

                    prevSpeed : 0,
                    beforeShow: function () {
                        // set size to (fancybox) img
                        // $(".fancybox-image").css({
                        //     "width": 800,
                        //     "height": 600
                        // });
                        // set size for parent container
                        this.width = 700;
                        this.height = 500; 
                    },
                    helpers: {
                        overlay: {
                          locked: false
                        }
                    }
                });


        });
  </script>



{% endblock %}

TEST/simple_forms/apps/core/templates/core/password_reset_complete.html
{% extends 'core/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}
{% load staticfiles %}
{% load i18n %}
{% load widget_tweaks %}
{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-4 col-sm-offset-4 col-xs-12 col-xs-offset-0">
            <div class="panel panel-default">
                <div class="panel-body">
                    <img class="img-responsive" style="margin-left: auto; margin-right:" src="{% static "img/logo22.jpg" %}" alt="Logo" />

                    <h3 class="text-center">Password reseted</h3>

                    <p>You can <a href="{% url "login_user" %}">sign in now</a></p>
                </div>
                <div class="panel-footer">
                    <p id="footer"> Don't have an account? <a href="{% url 'register' %}">Click here</a> to register.</p>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}